# Generated by Django 3.2.6 on 2021-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('sub_department', models.CharField(max_length=100, null=True)),
                ('office_shift', models.CharField(max_length=100, null=True)),
                ('reports_to', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('doj', models.DateField(null=True)),
                ('dob', models.DateField(null=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
