# Generated by Django 3.2.6 on 2021-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ManyToManyField(to='employee.Location'),
        ),
    ]
