# Generated by Django 3.2.6 on 2021-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20210831_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
