# Generated by Django 3.2.6 on 2021-08-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_location_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
