# Generated by Django 3.2.6 on 2021-08-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20210831_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='sub_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='employee.department'),
        ),
    ]
