# Generated by Django 3.2.6 on 2021-08-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20210831_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('starting_time', models.CharField(max_length=255)),
                ('closing_time', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_shift', to='employee.office_shift'),
        ),
    ]
