# Generated by Django 3.2.6 on 2021-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20210831_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_shift',
            name='closing_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='office_shift',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='office_shift',
            name='starting_time',
            field=models.DateTimeField(),
        ),
    ]
