# Generated by Django 3.2.6 on 2021-09-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reports_to',
        ),
    ]
